pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.config

// Writes the current palette into config snippets for other programs and
// asks them to reload. Files live in ~/.local/state/shell/theme/:
//   niri.kdl   include it last in niri's config (also sets the overview backdrop)
//   kitty.conf include it from kitty.conf
//   gtk3.css / gtk4.css   imported from ~/.config/gtk-{3,4}.0/gtk.css
//   colors.json  every palette value, for scripts
Singleton {
    id: root

    readonly property string dir: (Quickshell.env("XDG_STATE_HOME") || Quickshell.env("HOME") + "/.local/state") + "/shell/theme"
    property bool ready: false

    readonly property var m: Theme.m3
    readonly property var p: Theme.p
    // Re-render whenever any color (or the enabled set) changes.
    readonly property string signature: JSON.stringify([m, p, Theme.lightMode, Settings.d.templates])

    onSignatureChanged: debounce.restart()

    function enabled(name) {
        return Settings.d.templates[name] !== false;
    }

    function hex(c) {
        return String(c).slice(0, 7);
    }

    function alpha(c, a) {
        return hex(c) + Math.round(a * 255).toString(16).padStart(2, "0");
    }

    function niri() {
        return `// Generated by the shell from the current theme. Do not edit.
layout {
    focus-ring {
        active-gradient from="${hex(m.primary)}" to="${hex(m.tertiary)}" angle=45
        inactive-gradient from="${hex(m.surfaceContainerHigh)}" to="${hex(m.outlineVariant)}" angle=45 relative-to="workspace-view"
        urgent-color "${hex(m.error)}"
    }
    border {
        active-color "${hex(m.primary)}"
        inactive-color "${hex(m.surfaceContainerHigh)}"
        urgent-color "${hex(m.error)}"
    }
    tab-indicator {
        active-color "${hex(m.primary)}"
        inactive-color "${hex(m.primaryContainer)}"
        urgent-color "${hex(m.error)}"
    }
    insert-hint {
        color "${alpha(m.primary, 0.5)}"
    }
}

recent-windows {
    highlight {
        active-color "${hex(m.primary)}"
        urgent-color "${hex(m.error)}"
    }
}

overview {
    backdrop-color "${hex(m.surfaceContainerLowest)}"
}

// The shell's blurred wallpaper behind workspaces in the overview.
layer-rule {
    match namespace="^quickshell-backdrop$"
    place-within-backdrop true
}
`;
    }

    function kitty() {
        const dark = !Theme.lightMode;
        const ansi = [p.surface1, p.red, p.green, p.yellow, p.blue, p.pink, p.teal, p.subtext1, p.surface2, p.red, p.green, p.yellow, p.blue, p.pink, p.teal, p.subtext0];
        let s = `# Generated by the shell from the current theme. Do not edit.
foreground ${hex(m.onSurface)}
background ${hex(m.surface)}
selection_foreground ${hex(m.onSecondaryContainer)}
selection_background ${hex(m.secondaryContainer)}
cursor ${hex(m.primary)}
cursor_text_color ${hex(m.onPrimary)}
url_color ${hex(m.tertiary)}
active_border_color ${hex(m.primary)}
inactive_border_color ${hex(m.outlineVariant)}
bell_border_color ${hex(m.error)}
active_tab_foreground ${hex(m.onPrimary)}
active_tab_background ${hex(m.primary)}
inactive_tab_foreground ${hex(m.onSurfaceVariant)}
inactive_tab_background ${hex(m.surfaceContainer)}
tab_bar_background ${hex(m.surfaceContainerLowest)}
mark1_foreground ${hex(m.onPrimary)}
mark1_background ${hex(m.primary)}
`;
        ansi.forEach((c, i) => s += `color${i} ${hex(c)}\n`);
        return s;
    }

    function gtk(version) {
        const defs = {
            accent_color: m.primary,
            accent_bg_color: m.primary,
            accent_fg_color: m.onPrimary,
            destructive_color: m.error,
            destructive_bg_color: m.error,
            destructive_fg_color: m.onError,
            error_color: m.error,
            error_bg_color: m.error,
            error_fg_color: m.onError,
            success_color: p.green,
            warning_color: p.yellow,
            window_bg_color: m.surface,
            window_fg_color: m.onSurface,
            view_bg_color: m.surface,
            view_fg_color: m.onSurface,
            headerbar_bg_color: version === 3 ? m.surfaceContainer : m.surface,
            headerbar_fg_color: m.onSurface,
            headerbar_backdrop_color: m.surface,
            popover_bg_color: m.surfaceContainer,
            popover_fg_color: m.onSurface,
            card_bg_color: m.surfaceContainer,
            card_fg_color: m.onSurface,
            dialog_bg_color: m.surfaceContainerLow,
            dialog_fg_color: m.onSurface,
            sidebar_bg_color: m.surfaceContainerLow,
            sidebar_fg_color: m.onSurface,
            sidebar_backdrop_color: m.surface,
            sidebar_border_color: m.surface,
            secondary_sidebar_bg_color: m.surface,
            secondary_sidebar_fg_color: m.onSurface,
            theme_selected_bg_color: m.primary,
            theme_selected_fg_color: m.onPrimary,
            theme_unfocused_fg_color: m.onSurface,
            theme_unfocused_text_color: m.onSurface,
            theme_unfocused_bg_color: m.surface,
            theme_unfocused_base_color: m.surface,
            theme_unfocused_selected_bg_color: m.primary,
            theme_unfocused_selected_fg_color: m.onPrimary
        };
        let s = `/* Generated by the shell from the current theme. Do not edit. */\n\n`;
        for (const [k, v] of Object.entries(defs))
            s += `@define-color ${k} ${hex(v)};\n`;
        if (version === 4) {
            // libadwaita 1.6+ reads CSS variables too.
            s += "\n:root {\n";
            for (const [k, v] of Object.entries(defs))
                s += `    --${k.replace(/_/g, "-")}: ${hex(v)};\n`;
            s += "}\n";
        }
        return s;
    }

    function write() {
        if (!ready)
            return;
        if (enabled("niri")) {
            niriFile.setText(niri());
            niriReload.running = true;
        }
        if (enabled("kitty")) {
            kittyFile.setText(kitty());
            kittyReload.running = true;
        }
        if (enabled("gtk")) {
            gtk3File.setText(gtk(3));
            gtk4File.setText(gtk(4));
        }
        jsonFile.setText(JSON.stringify(Object.assign({
            mode: Theme.lightMode ? "light" : "dark",
            source: Theme.source,
            seed: Theme.seed
        }, {
            m3: m,
            palette: p
        }), null, 2));
    }

    Timer {
        id: debounce

        interval: 600
        onTriggered: root.write()
    }

    Process {
        command: ["mkdir", "-p", root.dir]
        running: true
        onExited: {
            root.ready = true;
            debounce.restart();
        }
    }

    FileView {
        id: niriFile

        path: root.dir + "/niri.kdl"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: kittyFile

        path: root.dir + "/kitty.conf"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk3File

        path: root.dir + "/gtk3.css"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk4File

        path: root.dir + "/gtk4.css"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: jsonFile

        path: root.dir + "/colors.json"
        atomicWrites: true
        printErrors: false
    }

    // niri watches its main config; included files may need a nudge.
    Process {
        id: niriReload

        command: ["niri", "msg", "action", "load-config-file"]
    }

    // kitty reloads its config (and includes) on SIGUSR1.
    Process {
        id: kittyReload

        command: ["pkill", "-USR1", "-x", "\\.?kitty(-wrapped)?"]
    }
}
